name: Plex Shuffler CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - development

jobs:
  test:
    name: Lint & Test Build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-20.04
    container: node:20.3.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        env:
          HUSKY: 0
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Formatting
        run: yarn format:check
      - name: Build
        run: yarn build

  build_and_push:
    name: Build & Publish Docker Images
    if: github.ref == 'refs/heads/development' && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            COMMIT_TAG=${{ github.sha }}
          tags: |
            douwjacobs/plex-shuffler:development
            douwjacobs/plex-shuffler:${{ github.sha }}
            ghcr.io/douwjacobs/plex-shuffler:development
            ghcr.io/douwjacobs/plex-shuffler:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
